title : Jason Frank
tagline: Numerical analysis, computational mathematics, complex systems
author :
  name : Jason Frank
  email : j.e.frank@uu.nl

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

gems:
  - jekyll-pandoc

markdown: pandoc
pandoc:
   extensions:
      - mathjax

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews 
gitstamps: yes
repo: https://github.com/jasonefrank/labnotebook # used in linking history

baseurl: '/'

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
